import java.util.Collections;
import java.util.Map;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 * Validates SQL generated by the AI before it reaches the database.
 *
 * This class contains technical security rules only. Business rules such as
 * joins, reporting logic, labels, and response language remain in DBLRULE and
 * are supplied to the AI by AiBridge.
 */
public class SqlGuard {

    private static final String[] FORBIDDEN_KEYWORDS = {
            "INSERT", "UPDATE", "DELETE", "DROP", "ALTER", "CREATE",
            "TRUNCATE", "EXEC", "EXECUTE", "GRANT", "REVOKE", "MERGE"
    };

    private static final Pattern SELECT_ONLY = Pattern.compile(
            "^\\s*SELECT\\b",
            Pattern.CASE_INSENSITIVE
    );

    private static final Pattern TABLE_PATTERN = Pattern.compile(
            "\\bFROM\\s+\"([^\"]+)\"|\\bJOIN\\s+\"([^\"]+)\"",
            Pattern.CASE_INSENSITIVE
    );

    public static class Result {
        public final boolean allowed;
        public final String reason;
        public final String sql;
        public final String language;
        public final String summary;
        public final String visualization;
        public final String xAxis;
        public final String yAxis;
        public final Map<String, String> buttons;
        public final Map<String, String> paging;

        /* Constructor used for validation failures. */
        Result(boolean allowed, String reason, String sql) {
            this(
                    allowed,
                    reason,
                    sql,
                    "",
                    null,
                    "auto",
                    null,
                    null,
                    Collections.<String, String>emptyMap(),
                    Collections.<String, String>emptyMap()
            );
        }

        /* Backward-compatible constructor for existing callers. */
        Result(
                boolean allowed,
                String reason,
                String sql,
                String summary,
                String visualization,
                String xAxis,
                String yAxis,
                Map<String, String> buttons,
                Map<String, String> paging
        ) {
            this(
                    allowed,
                    reason,
                    sql,
                    "",
                    summary,
                    visualization,
                    xAxis,
                    yAxis,
                    buttons,
                    paging
            );
        }

        /* Constructor that also carries the user's response language. */
        Result(
                boolean allowed,
                String reason,
                String sql,
                String language,
                String summary,
                String visualization,
                String xAxis,
                String yAxis,
                Map<String, String> buttons,
                Map<String, String> paging
        ) {
            this.allowed = allowed;
            this.reason = reason;
            this.sql = sql;
            this.language = language == null ? "" : language.trim();
            this.summary = summary;
            this.visualization = visualization == null || visualization.isEmpty()
                    ? "auto"
                    : visualization;
            this.xAxis = xAxis;
            this.yAxis = yAxis;
            this.buttons = buttons == null
                    ? Collections.<String, String>emptyMap()
                    : buttons;
            this.paging = paging == null
                    ? Collections.<String, String>emptyMap()
                    : paging;
        }
    }

    public static Result check(String sql) {
        if (sql == null || sql.trim().isEmpty()) {
            return new Result(false, "Empty SQL generated", sql);
        }

        String trimmedSql = sql.trim();
        String upperSql = trimmedSql.toUpperCase();

        if (upperSql.equals("REFUSED")
                || upperSql.startsWith("REFUSED_MODIFY")) {
            return new Result(
                    false,
                    "Question requires modifying data, which is not permitted",
                    sql
            );
        }

        if (upperSql.startsWith("REFUSED_UNAVAILABLE")
                || upperSql.startsWith("REFUSED_RESTRICTED")
                || upperSql.startsWith("REFUSED_TABLE")) {
            return new Result(
                    false,
                    "Requested table or data is restricted or not available",
                    sql
            );
        }

        if (!SELECT_ONLY.matcher(sql).find()) {
            return new Result(false, "Only SELECT statements are allowed", sql);
        }

        String checkedSql = sql.trim();

        if (checkedSql.endsWith(";")) {
            checkedSql = checkedSql.substring(
                    0,
                    checkedSql.length() - 1
            ).trim();
        } else if (checkedSql.contains(";")) {
            return new Result(
                    false,
                    "Statement chaining is not allowed",
                    sql
            );
        }

        String upperCheckedSql = checkedSql.toUpperCase();

        for (String keyword : FORBIDDEN_KEYWORDS) {
            Pattern keywordPattern = Pattern.compile(
                    "\\b" + keyword + "\\b"
            );

            if (keywordPattern.matcher(upperCheckedSql).find()) {
                return new Result(
                        false,
                        "Forbidden keyword: " + keyword,
                        checkedSql
                );
            }
        }

        Matcher tableMatcher = TABLE_PATTERN.matcher(checkedSql);
        boolean foundTable = false;

        while (tableMatcher.find()) {
            foundTable = true;

            String tableName = tableMatcher.group(1) != null
                    ? tableMatcher.group(1)
                    : tableMatcher.group(2);

            try {
                if (!AiBridge.isTableAllowed(tableName)) {
                    return new Result(
                            false,
                            "Table not allowed: " + tableName,
                            checkedSql
                    );
                }
            } catch (java.sql.SQLException exception) {
                return new Result(
                        false,
                        "Unable to verify table authorization",
                        checkedSql
                );
            }
        }

        if (!foundTable) {
            return new Result(
                    false,
                    "Could not identify a double-quoted table in the query",
                    checkedSql
            );
        }

        return new Result(true, "OK", checkedSql);
    }
}
